/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import org.junit.Test;
import static org.junit.Assert.*;

public class MonsterTest {
  @Test
  public void testAppHasAGreeting() {
    Monster MonsterTest = new Monster();
    assertNotNull("app should have a greeting", MonsterTest.toString());
  }
}
